// FeedbackReport → Jira create-issue payload.
//
// Kept as a pure function with no client and no clock so the triage view can show
// the exact bytes that will be POSTed. A preview that is regenerated by different
// code than the send path is a lie waiting to happen.

import type { FeedbackReport } from '../types';
import type { JiraConfig } from './config';
import { adfIssueDescription } from './adf';
import type { JiraIssueCreateRequest } from './types';

/**
 * Jira labels may not contain spaces — Jira rejects the whole request rather than
 * normalising, which is a 400 that looks like a mystery from the UI.
 */
export function toLabel(prefix: string, value: string): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return `${prefix}-${slug || 'unknown'}`;
}

export function feedbackLabels(report: FeedbackReport, config: JiraConfig): string[] {
  return [
    ...config.baseLabels,
    toLabel('kind', report.kind),
    toLabel('impact', report.impact),
    toLabel('area', report.area),
  ];
}

export function feedbackToJiraRequest(
  report: FeedbackReport,
  config: JiraConfig,
): JiraIssueCreateRequest {
  // Opting out of context sharing must actually withhold it. The checkbox is the
  // reporter's only lever over what leaves their browser, so it gates the payload
  // itself rather than merely hiding the block in the UI.
  const context: Record<string, string> = report.shareContext
    ? {
        Screen: `${report.context.screen} (${report.context.route})`,
        Role: report.context.role,
        'Reported by': report.reporter,
        'App version': report.context.appVersion,
        Viewport: report.context.viewport,
        Browser: report.context.userAgent,
        'Local report id': report.id,
      }
    : { 'Local report id': report.id };

  return {
    fields: {
      project: { key: config.projectKey },
      summary: report.title,
      description: adfIssueDescription(report.detail, context),
      issuetype: { name: config.issueTypeByKind[report.kind] },
      labels: feedbackLabels(report, config),
    },
  };
}
