/**
 * The /ops board view-model (myGFO Work Ledger design §7 — "the window").
 *
 * Pure shaping of the committed snapshot (public/ops-ledger.json, generated by
 * the Tech Log working repo's scripts/snapshot.mjs from the Obsidian vault).
 * The board is read-only by design: the vault is the desk, this is a window,
 * ~1 minute behind and honest about its own age.
 *
 * Lanes, in the design's priority order:
 *   1. waiting  — blocked on a human, Bryan first (he is the constraint, not the work)
 *   2. inFlight — a session holds a branch
 *   3. captured — ideas in the door, untriaged
 *   4. landed   — proven merged (landed_by = merge commit, written only by reconcile.mjs)
 * plus `backlog` (triaged, blocked on nobody) so no live row is invisible, and
 * the open Gaps register as a secondary strip (unioned, not mirrored — LG-10).
 */

export interface OpsRow {
  id: string;
  title: string;
  status: string;
  source: string;
  captured_on: string;
  blocked_on: string;
  branch: string;
  session: string;
  landed_by: string;
  refs: string[];
}

export interface OpsQuestion {
  id: string;
  title: string;
  owner?: string;
  status: string;
}

export interface OpsGap {
  id: string;
  title: string;
  severity?: string;
  status: string;
}

export interface OpsSnapshot {
  generated_at: string;
  rows: OpsRow[];
  questions: OpsQuestion[];
  gaps: OpsGap[];
}

export interface WaitingItem {
  kind: 'ledger' | 'question';
  id: string;
  title: string;
  who: string;
  since: string;
  daysWaiting: number;
  refs: string[];
}

export interface BoardRow {
  id: string;
  title: string;
  source: string;
  since: string;
  daysWaiting: number;
  branch: string;
  session: string;
  landedBy: string;
  refs: string[];
}

export interface OpsBoard {
  waiting: WaitingItem[];
  inFlight: BoardRow[];
  captured: BoardRow[];
  backlog: BoardRow[];
  landed: BoardRow[];
  gaps: OpsGap[];
  parkedCount: number;
  droppedCount: number;
  totalRows: number;
  snapshotAgeMinutes: number;
  generatedAt: string;
}

const WHO_LABEL: Record<string, string> = {
  bryan: 'Bryan',
  dom: 'DOM',
  'chief-pilot': 'Chief Pilot',
  counsel: 'Counsel',
  camp: 'CAMP',
};

// Rows in these states are done moving; nothing about them waits on anyone.
const SETTLED = new Set(['landed', 'parked', 'dropped']);

const DAY_MS = 86_400_000;

function daysSince(iso: string, nowMs: number): number {
  const t = Date.parse(iso);
  if (Number.isNaN(t)) return 0;
  return Math.max(0, Math.floor((nowMs - t) / DAY_MS));
}

function toBoardRow(r: OpsRow, nowMs: number): BoardRow {
  return {
    id: r.id,
    title: r.title,
    source: r.source,
    since: r.captured_on,
    daysWaiting: daysSince(r.captured_on, nowMs),
    branch: r.branch,
    session: r.session,
    landedBy: r.landed_by ? r.landed_by.slice(0, 7) : '',
    refs: r.refs ?? [],
  };
}

export function buildOpsBoard(snap: OpsSnapshot, nowMs: number): OpsBoard {
  const rows = snap.rows ?? [];
  const live = rows.filter((r) => !SETTLED.has(r.status));

  // A question mirrored by a LIVE ledger row (via refs) appears once — the
  // ledger row wins while it carries queue state. A settled (parked/dropped/
  // landed) row carries none, so its refs must NOT suppress a still-open
  // question — that would be the board lying by omission.
  const mirrored = new Set(live.flatMap((r) => r.refs ?? []));

  const waiting: WaitingItem[] = [
    ...live
      .filter((r) => r.blocked_on && r.blocked_on !== 'nobody')
      .map((r) => ({
        kind: 'ledger' as const,
        id: r.id,
        title: r.title,
        who: WHO_LABEL[r.blocked_on] ?? r.blocked_on,
        since: r.captured_on,
        daysWaiting: daysSince(r.captured_on, nowMs),
        refs: r.refs ?? [],
      })),
    ...(snap.questions ?? [])
      .filter((q) => !mirrored.has(q.id))
      .map((q) => ({
        kind: 'question' as const,
        id: q.id,
        title: q.title,
        who: q.owner ?? '?',
        since: '',
        daysWaiting: 0,
        refs: [],
      })),
  ].sort((a, b) => {
    const aB = a.who === 'Bryan' ? 0 : 1;
    const bB = b.who === 'Bryan' ? 0 : 1;
    if (aB !== bB) return aB - bB;
    return (a.since || '9999').localeCompare(b.since || '9999');
  });

  // A live row blocked on a human belongs to the hero lane alone — listing it
  // again under Captured/Backlog would double-count the same wait.
  const inWaiting = new Set(waiting.filter((w) => w.kind === 'ledger').map((w) => w.id));
  const byStatus = (s: string) =>
    rows.filter((r) => r.status === s && !inWaiting.has(r.id)).map((r) => toBoardRow(r, nowMs));

  const ageMs = Date.parse(snap.generated_at);
  const snapshotAgeMinutes = Number.isNaN(ageMs) ? -1 : Math.max(0, Math.round((nowMs - ageMs) / 60_000));

  return {
    waiting,
    inFlight: byStatus('in-flight'),
    captured: byStatus('captured'),
    backlog: rows
      .filter((r) => r.status === 'triaged' && !inWaiting.has(r.id))
      .map((r) => toBoardRow(r, nowMs)),
    landed: byStatus('landed'),
    gaps: snap.gaps ?? [],
    parkedCount: rows.filter((r) => r.status === 'parked').length,
    droppedCount: rows.filter((r) => r.status === 'dropped').length,
    totalRows: rows.length,
    snapshotAgeMinutes,
    generatedAt: snap.generated_at,
  };
}
