// Seed data: the real Scheduler Daily / Monthly / Quarterly checklists + the Domestic
// per-trip checklist, transcribed from docs/scheduling/foundation-scheduling-workspace-design.md
// (§1, "the nine source checklists") as editable template DATA. Nothing about checklist
// content lives in engine/store logic — this file is the seam the department will edit
// via a UI in a later slice (D9: templates are editable data, role-gated, versioned).
import type { ChecklistTemplate, TaskDefinition } from '../engine';
import type { SchedulingStore } from './types';
import { parseTemplate } from './validate';

const EFFECTIVE_FROM = '2026-01-01T00:00:00.000Z';

// Every per-trip checklist delivers the crew brief in-system (2026-07-02 review, item 2).
// Completing this task fires the handoff event the pilot Flight Hub's Trip-brief panel reads;
// the human conversation stays — this is the digital delivery of what was covered.
const SEND_CREW_BRIEF = {
  id: 'send-crew-brief',
    bindTo: 'crew',
  title: 'Send crew brief',
  description:
    'Deliver the trip brief to the crew in the system — schedule, pax, handling, and anything covered verbally.',
  ownerRole: 'scheduling',
  category: 'crew',
  order: 99, // always sorts last within the checklist
  dueRule: { kind: 'hoursBeforeEtd', hours: 48 },
  requiresAck: false, // the PILOT acks the delivered event in the Flight Hub, not this task
  handoffTarget: { kind: 'role', value: 'pilot', channel: 'teams' },
} as const;

// Trip-prep tasks that apply to EVERY trip regardless of type. Like SEND_CREW_BRIEF, these are
// shared definitions spread into each per-trip template (domestic / international / DASSP) so
// "all trips" coverage lives in one place in the seed. Transcribed from the department's Portal
// trip-checklist examples (Portal-TripChecklistExamples.xlsx, 2026-07-07). The Excel's exact-airport
// and prefix (K-except-KLUK) per-leg tasks (FBO, hangar, KLUK fuel, KBOS PPR, KLGA ARO) plus the
// re-triggering pax-forms task now ship below as PER_AIRPORT_TASKS on the per-airport engine.
const ALL_TRIPS_TASKS: TaskDefinition[] = [
  {
    id: 'confirm-catering-needs',
    title: 'Confirm catering needs',
    // Department checklist scopes this "each leg — all airports". The per-airport engine fans out by
    // an airport MATCH (exact / prefix), so "every leg regardless of airport" is not yet expressible;
    // kept trip-level pending an any-airport matcher (audit #2).
    description: 'Confirm catering for the trip. (Per-leg catering needs an any-airport match rule the engine does not have yet.)',
    ownerRole: 'scheduling',
    category: 'ops',
    order: 50,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 7 },
    requiresAck: false,
  },
  {
    id: 'push-to-foreflight',
    title: 'Push trip to ForeFlight',
    ownerRole: 'scheduling',
    category: 'ops',
    order: 51,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 5 },
    requiresAck: false,
  },
  {
    id: 'final-trip-confirmation-admin',
    title: 'Final trip confirmation with admin',
    ownerRole: 'scheduling',
    category: 'handoff',
    order: 52,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 2 },
    requiresAck: true,
    handoffTarget: { kind: 'role', value: 'executive-assistant', channel: 'email' },
  },
  {
    id: 'passenger-itinerary-received',
    title: 'Passenger itinerary received',
    ownerRole: 'scheduling',
    category: 'ops',
    order: 53,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
    requiresAck: true,
  },
  {
    id: 'crew-hotel-information-obtained',
    bindTo: 'crew',
    title: 'Crew hotel information obtained',
    ownerRole: 'scheduling',
    category: 'crew',
    order: 54,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
    requiresAck: false,
  },
];

// Per-leg / exact-airport + re-trigger tasks from the department Portal trip-checklist examples
// (Phase 2). Shared into every per-trip template like ALL_TRIPS_TASKS — a K airport is a K airport
// regardless of trip type. `appliesTo` drives per-leg fan-out (one instance per matching
// leg-endpoint); `reTriggerOn` re-flags a completed instance when the trip changes. See
// docs/scheduling/2026-07-07-per-leg-reflag-design.md.
const PER_AIRPORT_TASKS: TaskDefinition[] = [
  {
    id: 'fbo-handling',
    title: 'Arrange FBO handling',
    ownerRole: 'scheduling',
    category: 'handling',
    order: 60,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
    requiresAck: false,
    appliesTo: { endpoint: 'both', airport: { kind: 'prefix', prefix: 'K', except: ['KLUK'] } },
    reTriggerOn: ['legScheduleChange', 'aircraftChange'],
  },
  {
    id: 'hangar-needed',
    title: 'Confirm hangar needs',
    ownerRole: 'scheduling',
    category: 'handling',
    order: 61,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
    requiresAck: false,
    appliesTo: { endpoint: 'both', airport: { kind: 'prefix', prefix: 'K', except: ['KLUK'] } },
    reTriggerOn: ['legScheduleChange', 'aircraftChange'],
  },
  {
    id: 'fuel-load-luk',
    title: 'Confirm fuel load (KLUK departure)',
    ownerRole: 'scheduling',
    category: 'fuel',
    order: 62,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
    requiresAck: false,
    appliesTo: { endpoint: 'departure', airport: { kind: 'exact', icao: 'KLUK' } },
  },
  {
    id: 'kbos-ppr',
    title: 'Obtain KBOS PPR',
    ownerRole: 'scheduling',
    category: 'permits',
    order: 63,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 7 },
    requiresAck: true,
    appliesTo: { endpoint: 'arrival', airport: { kind: 'exact', icao: 'KBOS' } },
    reTriggerOn: ['legScheduleChange', 'aircraftChange'],
  },
  {
    id: 'klga-aro-slot',
    title: 'Obtain KLGA ARO slot',
    ownerRole: 'scheduling',
    category: 'permits',
    order: 64,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 3 },
    requiresAck: true,
    appliesTo: { endpoint: 'both', airport: { kind: 'exact', icao: 'KLGA' } },
    reTriggerOn: ['legScheduleChange', 'aircraftChange'],
  },
  {
    id: 'pax-forms',
    bindTo: 'person',
    // Excel left the deadline blank; assumed 1 business day before departure (flagged for the DOM).
    title: 'Confirm passenger forms',
    description: 'Confirm all passenger forms are on file. Re-flags when a passenger is added.',
    ownerRole: 'scheduling',
    category: 'ops',
    order: 65,
    dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
    requiresAck: false,
    reTriggerOn: ['passengerChange'],
  },
];

const SCHEDULER_DAILY: ChecklistTemplate = {
  id: 'scheduler-daily',
  name: 'Scheduler Daily Checklist',
  triggerType: 'recurring',
  scope: 'daily',
  version: 1,
  status: 'published',
  effectiveFrom: EFFECTIVE_FROM,
  taskDefinitions: [
    {
      id: 'notams-weather-intake',
      title: 'Pull NOTAMs & weather for tomorrow’s departures',
      ownerRole: 'scheduling',
      category: 'ops-intake',
      order: 1,
      dueRule: { kind: 'dayOfTimeLocal', time: '08:00' },
      requiresAck: false,
    },
    {
      id: 'fuel-luk',
      title: 'Update Lunken (LUK) fuel price in FuelerLinx',
      ownerRole: 'scheduling',
      category: 'fuel',
      order: 2,
      dueRule: { kind: 'weekday', day: 'MON' },
      requiresAck: false,
    },
    {
      id: 'currency-report-mon',
      title: 'Run pilot currency report',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 3,
      dueRule: { kind: 'weekday', day: 'MON' },
      requiresAck: false,
    },
    {
      id: 'currency-report-thu',
      title: 'Run pilot currency report',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 4,
      dueRule: { kind: 'weekday', day: 'THU' },
      requiresAck: false,
    },
    {
      id: 'trip-sheet-to-ea',
      title: 'Hand off trip sheet to Executive Assistant',
      ownerRole: 'scheduling',
      category: 'handoff',
      order: 5,
      dueRule: { kind: 'dayOfTimeLocal', time: '14:00' },
      requiresAck: true,
      handoffTarget: { kind: 'role', value: 'executive-assistant', channel: 'email' },
    },
    {
      id: 'brief',
      title: 'Send next-day crew brief',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 6,
      dueRule: { kind: 'dayOfTimeLocal', time: '15:00' },
      requiresAck: true,
      escalation: {
        deadline: { kind: 'dayOfTimeLocal', time: '17:00' },
        notifyRole: 'scheduling',
        reason: 'Crew has not acknowledged the next-day brief',
      },
      handoffTarget: { kind: 'role', value: 'pilot', channel: 'teams' },
    },
  ],
};

const SCHEDULER_MONTHLY: ChecklistTemplate = {
  id: 'scheduler-monthly',
  name: 'Scheduler Monthly Checklist',
  triggerType: 'recurring',
  scope: 'monthly',
  version: 1,
  status: 'published',
  effectiveFrom: EFFECTIVE_FROM,
  taskDefinitions: [
    {
      id: 'flight-log-audit',
      title: 'Audit flight logs for the prior month',
      description: 'Gate item — downstream monthly reports depend on a clean flight-log audit.',
      ownerRole: 'scheduling',
      category: 'compliance',
      order: 1,
      dueRule: { kind: 'dayOfMonth', day: 5, when: 'onOrBefore' },
      requiresAck: true,
    },
    {
      id: 'imputed-income-report',
      title: 'Prepare and distribute imputed income report',
      ownerRole: 'scheduling',
      category: 'finance',
      order: 2,
      dueRule: { kind: 'dayOfMonth', day: 15, when: 'before' },
      requiresAck: true,
      handoffTarget: { kind: 'dept', value: 'payroll', channel: 'email' },
    },
    {
      id: 'chargeback-report',
      title: 'Prepare and distribute chargeback report',
      ownerRole: 'scheduling',
      category: 'finance',
      order: 3,
      dueRule: { kind: 'dayOfMonth', day: 25, when: 'around' },
      requiresAck: true,
      handoffTarget: { kind: 'dept', value: 'finance', channel: 'email' },
    },
    {
      id: 'pilot-logbook-distribution',
      title: 'Distribute pilot logbooks for the prior month',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 4,
      dueRule: { kind: 'dayOfMonth', day: 5, when: 'onOrBefore' },
      requiresAck: false,
      handoffTarget: { kind: 'role', value: 'pilot', channel: 'email' },
    },
  ],
};

const SCHEDULER_QUARTERLY: ChecklistTemplate = {
  id: 'scheduler-quarterly',
  name: 'Scheduler Quarterly Checklist',
  triggerType: 'recurring',
  scope: 'quarterly',
  version: 1,
  status: 'published',
  effectiveFrom: EFFECTIVE_FROM,
  taskDefinitions: [
    {
      id: 'fos-access-audit',
      title: 'Audit FOS user access list',
      ownerRole: 'scheduling',
      category: 'compliance',
      order: 1,
      dueRule: { kind: 'quarterWeek', week: 1 },
      requiresAck: true,
    },
    {
      id: 'eu-ets-update',
      title: 'File EU ETS emissions update',
      description: 'Annual item, tracked on the quarterly board so it is never missed.',
      ownerRole: 'scheduling',
      category: 'compliance',
      order: 2,
      dueRule: { kind: 'annualDate', month: 3, day: 31 },
      requiresAck: true,
      handoffTarget: { kind: 'dept', value: 'compliance', channel: 'email' },
    },
    {
      id: 'sifl-rate-update',
      title: 'Update SIFL rates',
      ownerRole: 'scheduling',
      category: 'finance',
      order: 3,
      dueRule: { kind: 'quarterWeek', week: 1 },
      requiresAck: false,
    },
    {
      id: 'passport-review',
      title: 'Review crew & frequent-passenger passport expirations',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 4,
      dueRule: { kind: 'quarterWeek', week: 2 },
      requiresAck: true,
    },
  ],
};

const DOMESTIC_PER_TRIP: ChecklistTemplate = {
  id: 'domestic-per-trip',
  name: 'Domestic Flight Checklist',
  triggerType: 'per_trip',
  scope: 'domestic',
  version: 1,
  status: 'published',
  effectiveFrom: EFFECTIVE_FROM,
  taskDefinitions: [
    {
      id: 'airport-suitability',
      title: 'Confirm airport suitability for tail/aircraft type',
      ownerRole: 'scheduling',
      category: 'ops',
      order: 1,
      dueRule: { kind: 'hoursBeforeEtd', hours: 24 },
      requiresAck: true,
    },
    {
      id: 'notam-tfr-check',
      title: 'Check NOTAMs/TFRs along the route',
      ownerRole: 'scheduling',
      category: 'ops',
      order: 2,
      dueRule: { kind: 'hoursBeforeEtd', hours: 12 },
      requiresAck: false,
    },
    {
      id: 'fuel-confirm',
      title: 'Confirm Jet-A fuel availability at destination',
      ownerRole: 'scheduling',
      category: 'fuel',
      order: 3,
      dueRule: { kind: 'hoursBeforeEtd', hours: 12 },
      requiresAck: false,
    },
    {
      id: 'seven-pax-g650-handling',
      title: 'Arrange special handling for 7+ pax G650ER departure',
      description: 'Focus item: 7-pax G650 loading requires additional ground handling coordination.',
      ownerRole: 'scheduling',
      category: 'ops',
      order: 4,
      dueRule: { kind: 'hoursBeforeEtd', hours: 24 },
      requiresAck: true,
      condition: {
        kind: 'allOf',
        conditions: [
          { kind: 'paxCountAtLeast', value: 7 },
          { kind: 'aircraftTypeEquals', value: 'G650ER' },
        ],
      },
      handoffTarget: { kind: 'role', value: 'pilot', channel: 'teams' },
    },
    ...PER_AIRPORT_TASKS,
    ...ALL_TRIPS_TASKS,
    SEND_CREW_BRIEF,
  ],
};

const INTERNATIONAL_PER_TRIP: ChecklistTemplate = {
  id: 'international-per-trip',
  name: 'International Flight Checklist',
  triggerType: 'per_trip',
  scope: 'international',
  version: 1,
  status: 'published',
  effectiveFrom: EFFECTIVE_FROM,
  taskDefinitions: [
    // -- Base tasks (every international trip) --
    {
      id: 'intl-trip-sheet-to-uv',
      title: 'Send trip sheet to Universal Aviation (UV)',
      ownerRole: 'scheduling',
      category: 'comms',
      order: 1,
      dueRule: { kind: 'monthsBeforeEtd', months: 1 },
      requiresAck: false,
      handoffTarget: { kind: 'dept', value: 'universal-aviation', channel: 'email' },
    },
    {
      id: 'intl-crew-pax-info-to-uv',
      title: 'Send crew & passenger info to Universal Aviation (UV)',
      ownerRole: 'scheduling',
      category: 'comms',
      order: 2,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 10 },
      requiresAck: false,
      handoffTarget: { kind: 'dept', value: 'universal-aviation', channel: 'email' },
    },
    {
      id: 'intl-confirm-pic-international-captain',
    bindTo: 'crew',
      title: 'Confirm PIC is a qualified International Captain',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 3,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 10 },
      requiresAck: true,
    },
    {
      id: 'intl-crew-passports-visas',
    bindTo: 'crew',
      title: 'Confirm CREW passports & visas',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 4,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 10 },
      requiresAck: true,
    },
    {
      id: 'intl-pax-passports-visas',
    bindTo: 'person',
      title: 'Confirm PAX passports & visas',
      description: 'One item per person aboard; the document gate on that person is the same item (D110 slice 2).',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 5,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 10 },
      requiresAck: true,
    },
    {
      id: 'intl-apis-cross-check',
      title: 'Cross-check outbound APIS from Universal Aviation (UV)',
      description: 'Deferred follow-on: permits/APIS are not first-class entities yet — cross-check against the UV submission manually.',
      ownerRole: 'scheduling',
      category: 'customs',
      order: 6,
      dueRule: { kind: 'hoursBeforeEtd', hours: 24 },
      requiresAck: true,
    },
    {
      id: 'intl-edocs-packet',
      title: 'Assemble E-docs packet (GenDec, Blue Sheet, crew trip sheet)',
      ownerRole: 'scheduling',
      category: 'customs',
      order: 7,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
      requiresAck: true,
    },
    // -- Country-conditional tasks --
    {
      id: 'intl-china-arrival-card',
      title: 'PAX complete China Arrival Card; verify passports have 6-month validity',
      ownerRole: 'scheduling',
      category: 'customs',
      order: 8,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
      requiresAck: true,
      condition: { kind: 'routeTouchesCountry', country: 'CN' },
    },
    {
      id: 'intl-uk-eta',
      title: 'Confirm UK ETA for pax & crew (unless transit-only fuel stop)',
      ownerRole: 'scheduling',
      category: 'permits',
      order: 9,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
      requiresAck: true,
      condition: { kind: 'routeTouchesCountry', country: 'GB' },
    },
    {
      id: 'intl-mexico-aiu-permit',
      title: 'Carry current + prior AIU landing permit if Mexico visited within 180 days',
      ownerRole: 'scheduling',
      category: 'permits',
      order: 10,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
      requiresAck: true,
      condition: { kind: 'routeTouchesCountry', country: 'MX' },
    },
    {
      id: 'intl-singapore-sgac',
      title: 'Submit Singapore Arrival Card (SGAC) within 3 days of arrival',
      ownerRole: 'scheduling',
      category: 'customs',
      order: 11,
      dueRule: { kind: 'hoursBeforeEtd', hours: 72 },
      requiresAck: true,
      condition: { kind: 'routeTouchesCountry', country: 'SG' },
    },
    {
      id: 'intl-philippines-bio-pages',
      title: 'Send passport bio pages to UV ≥24h before RPLL arrival',
      ownerRole: 'scheduling',
      category: 'customs',
      order: 12,
      dueRule: { kind: 'hoursBeforeEtd', hours: 24 },
      requiresAck: true,
      condition: { kind: 'routeTouchesCountry', country: 'PH' },
      handoffTarget: { kind: 'dept', value: 'universal-aviation', channel: 'email' },
    },
    {
      id: 'intl-canada-eta-canpass',
      title: 'Obtain eTA / provide CANPASS arrival info',
      ownerRole: 'scheduling',
      category: 'permits',
      order: 13,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
      requiresAck: true,
      condition: { kind: 'routeTouchesCountry', country: 'CA' },
    },
    {
      id: 'intl-india-trip-request',
      title: 'Send India trip request to UV ASAP — 7 working days (25 for military PPR)',
      ownerRole: 'scheduling',
      category: 'permits',
      order: 14,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 7 },
      requiresAck: true,
      condition: { kind: 'routeTouchesCountry', country: 'IN' },
      handoffTarget: { kind: 'dept', value: 'universal-aviation', channel: 'email' },
    },
    // -- International-only tasks from the department Portal trip-checklist examples (2026-07-07) --
    {
      id: 'intl-schedule-brief',
      title: 'Schedule international trip brief',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 15,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 10 },
      requiresAck: true,
    },
    {
      id: 'intl-mark-post-rest-off',
      title: 'Mark 48h post-trip rest as off in the schedule',
      ownerRole: 'scheduling',
      category: 'crew',
      order: 16,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 7 },
      requiresAck: false,
    },
    {
      id: 'intl-trip-binder-printed',
      title: 'Print international trip binder',
      ownerRole: 'scheduling',
      category: 'customs',
      order: 17,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 1 },
      requiresAck: false,
    },
    ...PER_AIRPORT_TASKS,
    ...ALL_TRIPS_TASKS,
    SEND_CREW_BRIEF,
  ],
};

const DASSP_PER_TRIP: ChecklistTemplate = {
  id: 'dassp-per-trip',
  name: 'Critical DCA / DASSP Checklist',
  triggerType: 'per_trip',
  scope: 'dca_dassp',
  version: 1,
  status: 'published',
  effectiveFrom: EFFECTIVE_FROM,
  taskDefinitions: [
    {
      id: 'dassp-tsa-inspection-request',
      title: 'Submit initial TSA inspection service request',
      ownerRole: 'scheduling',
      category: 'security',
      order: 1,
      dueRule: { kind: 'businessDaysBeforeEtd', days: 7 },
      requiresAck: false,
    },
    {
      id: 'dassp-aro-slot',
      title: 'Obtain ARO slot number (goes in flight-plan remarks)',
      ownerRole: 'scheduling',
      category: 'security',
      order: 2,
      dueRule: { kind: 'hoursBeforeEtd', hours: 72 },
      requiresAck: false,
    },
    {
      id: 'dassp-flight-authorization',
      title: 'Obtain DASSP Flight Authorization #',
      description: 'SSI: never email or put in flight-plan remarks — provide verbally to the Washington FDU only.',
      ownerRole: 'scheduling',
      category: 'security',
      order: 3,
      dueRule: { kind: 'hoursBeforeEtd', hours: 24 },
      requiresAck: true,
    },
    {
      id: 'dassp-confirm-gateway-fbo',
      title: 'Confirm gateway FBO (Signature DCA)',
      ownerRole: 'scheduling',
      category: 'permits',
      order: 4,
      dueRule: { kind: 'hoursBeforeEtd', hours: 24 },
      requiresAck: false,
    },
    {
      id: 'dassp-email-slot-and-authorization',
      title: 'Email crew the ARO slot #(s); email TSA the Authorization document',
      ownerRole: 'scheduling',
      category: 'comms',
      order: 5,
      dueRule: { kind: 'hoursBeforeEtd', hours: 12 },
      requiresAck: false,
      handoffTarget: { kind: 'role', value: 'pilot', channel: 'email' },
    },
    {
      id: 'dassp-file-icao-ifr-plan',
      title: 'File ICAO IFR flight plan to Washington Center FDU (2–22h window)',
      ownerRole: 'pilot',
      category: 'comms',
      order: 6,
      dueRule: { kind: 'hoursBeforeEtd', hours: 2 },
      requiresAck: false,
    },
    {
      id: 'dassp-tsa-screening',
      title: 'Complete TSA screening of aircraft, crew & passengers',
      ownerRole: 'pilot',
      category: 'security',
      order: 7,
      dueRule: { kind: 'hoursBeforeEtd', hours: 1 },
      requiresAck: true,
      escalation: {
        deadline: { kind: 'hoursBeforeEtd', hours: 0.5 },
        notifyRole: 'scheduling',
        reason: 'TSA screening has not been acknowledged as complete this close to ETD',
      },
      handoffTarget: { kind: 'role', value: 'pilot', channel: 'teams' },
    },
    {
      id: 'dassp-ncrcc-release-call',
      title: 'Call NCRCC to confirm aircraft release before departure',
      description: 'Hard pre-departure gate — the aircraft may not depart DCA without NCRCC release confirmation.',
      ownerRole: 'pilot',
      category: 'security',
      order: 8,
      dueRule: { kind: 'hoursBeforeEtd', hours: 1 },
      requiresAck: true,
    },
    ...PER_AIRPORT_TASKS,
    ...ALL_TRIPS_TASKS,
    SEND_CREW_BRIEF,
  ],
};

export const SEED_TEMPLATES: ChecklistTemplate[] = [
  SCHEDULER_DAILY,
  SCHEDULER_MONTHLY,
  SCHEDULER_QUARTERLY,
  DOMESTIC_PER_TRIP,
  INTERNATIONAL_PER_TRIP,
  DASSP_PER_TRIP,
];

export async function seedTemplates(store: SchedulingStore): Promise<void> {
  for (const raw of SEED_TEMPLATES) {
    const t = parseTemplate(raw); // validate content before persisting
    await store.saveTemplate(t);
  }
}
