import { describe, it, expect } from 'vitest';
import {
  buildSignedPayload, canonicalPayloadString, computeContentHash, hashSignedRecord,
  verifyContentHash, SIGNED_PAYLOAD_VERSION, type SignedPayload,
} from './contentHash';
import goldenVectors from '../../../../docs/tech-log/handover/signing-golden-vectors.json';

const BASE = {
  entity: 'MaintenanceRelease',
  entityId: 'REL-2026-0417',
  signerOid: '3f2a1b7c-9d4e-4a11-8c22-0b7d5e6f8a90',
  certNumber: 'A&P 3412887',
  intent: 'I certify this aircraft is approved for return to service with respect to the work performed.',
  signedAtUtc: '2026-07-14T16:32:05.000Z',
};

/**
 * The golden vectors are generated by scripts/gen-signing-vectors.mjs — a separate, plain-JS
 * implementation. Checking this module against them proves two independent implementations agree,
 * which is the exact property the production build has to satisfy (iPad client vs server
 * recompute). If these fail, one side's canonicalization drifted.
 */
describe('golden vectors (cross-implementation agreement)', () => {
  it('the fixture pins the spec the production build must implement', () => {
    expect(goldenVectors.spec).toEqual({
      canonicalization: 'RFC 8785 (JCS)', digest: 'SHA-256', encoding: 'UTF-8', output: 'lowercase hex',
    });
    expect(goldenVectors.payloadVersion).toBe(SIGNED_PAYLOAD_VERSION);
    expect(goldenVectors.vectors.length).toBeGreaterThanOrEqual(10);
  });

  it.each(goldenVectors.vectors.map((v) => [v.id, v] as const))(
    'reproduces vector %s',
    (_id, v) => {
      const payload = v.payload as unknown as SignedPayload;
      expect(canonicalPayloadString(payload)).toBe(v.canonical);
      expect(computeContentHash(payload)).toBe(v.sha256);
    },
  );

  it('every vector hash is a distinct lowercase 64-hex digest', () => {
    const hashes = goldenVectors.vectors.map((v) => v.sha256);
    for (const h of hashes) expect(h).toMatch(/^[0-9a-f]{64}$/);
    expect(new Set(hashes).size).toBe(hashes.length);
  });
});

describe('canonicalization invariants', () => {
  it('key insertion order does not change the hash', () => {
    // The whole reason JSON.stringify is banned for this: same data, different construction order.
    const a: SignedPayload = { v: 1, entity: 'Defect', entityId: 'D1', signerOid: 'oid-1', intent: 'x', signedAtUtc: '2026-07-14T00:00:00.000Z' };
    const b = { signedAtUtc: '2026-07-14T00:00:00.000Z', intent: 'x', signerOid: 'oid-1', entityId: 'D1', entity: 'Defect', v: 1 } as SignedPayload;
    expect(JSON.stringify(a)).not.toBe(JSON.stringify(b)); // stringify disagrees...
    expect(computeContentHash(a)).toBe(computeContentHash(b)); // ...canonicalization does not.
  });

  it('sorts nested object keys at every level', () => {
    const p = buildSignedPayload({ ...BASE, fields: { zulu: { yankee: 1, alpha: 2 }, alpha: 3 } });
    expect(canonicalPayloadString(p)).toContain('"fields":{"alpha":3,"zulu":{"alpha":2,"yankee":1}}');
  });

  it('emits non-ASCII as UTF-8, not \\u escapes', () => {
    const p = buildSignedPayload({ ...BASE, intent: 'José — 検査完了' });
    expect(canonicalPayloadString(p)).toContain('José — 検査完了');
  });

  it('an omitted optional field and an explicit null are different payloads', () => {
    const omitted = buildSignedPayload({ ...BASE, certNumber: undefined });
    const nulled = { ...omitted, certNumber: null } as unknown as SignedPayload;
    expect(computeContentHash(omitted)).not.toBe(computeContentHash(nulled));
  });
});

describe('buildSignedPayload', () => {
  it('omits absent optional fields rather than nulling them', () => {
    const p = buildSignedPayload({ ...BASE, certNumber: undefined });
    expect('certNumber' in p).toBe(false);
    expect('attachmentSha256' in p).toBe(false);
    expect('fields' in p).toBe(false);
  });

  it('keeps an empty-string certNumber, which is not the same as absent', () => {
    const p = buildSignedPayload({ ...BASE, certNumber: '' });
    expect(p.certNumber).toBe('');
    expect(computeContentHash(p)).not.toBe(computeContentHash(buildSignedPayload({ ...BASE, certNumber: undefined })));
  });

  it('sorts attachment digests so upload order cannot change the hash', () => {
    const one = buildSignedPayload({ ...BASE, attachmentSha256: ['ff', '00', '7a'] });
    const two = buildSignedPayload({ ...BASE, attachmentSha256: ['7a', 'ff', '00'] });
    expect(one.attachmentSha256).toEqual(['00', '7a', 'ff']);
    expect(computeContentHash(one)).toBe(computeContentHash(two));
  });

  it('does not mutate the caller’s attachment array', () => {
    const input = ['ff', '00'];
    buildSignedPayload({ ...BASE, attachmentSha256: input });
    expect(input).toEqual(['ff', '00']);
  });

  it('treats an empty attachment list and empty fields as absent', () => {
    const p = buildSignedPayload({ ...BASE, attachmentSha256: [], fields: {} });
    expect('attachmentSha256' in p).toBe(false);
    expect('fields' in p).toBe(false);
  });

  it('stamps the payload version', () => {
    expect(buildSignedPayload(BASE).v).toBe(SIGNED_PAYLOAD_VERSION);
  });

  it('changing any covered field changes the hash', () => {
    const base = hashSignedRecord(BASE);
    expect(hashSignedRecord({ ...BASE, entityId: 'REL-2026-0418' })).not.toBe(base);
    expect(hashSignedRecord({ ...BASE, signerOid: 'someone-else' })).not.toBe(base);
    expect(hashSignedRecord({ ...BASE, signedAtUtc: '2026-07-14T16:32:06.000Z' })).not.toBe(base);
    expect(hashSignedRecord({ ...BASE, intent: `${BASE.intent} ` })).not.toBe(base);
    expect(hashSignedRecord({ ...BASE, certNumber: 'A&P 0000000' })).not.toBe(base);
  });
});

describe('verifyContentHash', () => {
  it('accepts a matching hash and is case-insensitive on the expected value', () => {
    const p = buildSignedPayload(BASE);
    const h = computeContentHash(p);
    expect(verifyContentHash(p, h)).toBe(true);
    expect(verifyContentHash(p, h.toUpperCase())).toBe(true);
  });

  it('rejects a payload altered after signing — the server-side recompute case', () => {
    const signed = buildSignedPayload(BASE);
    const h = computeContentHash(signed);
    const tampered = { ...signed, entityId: 'REL-2026-9999' };
    expect(verifyContentHash(tampered, h)).toBe(false);
  });
});
