// myGFO-owned side of the "documents into ForeFlight" story: unlike the trip sheet,
// itinerary/travel-document content is data myGFO already collects itself (see
// PassengerFormContext / PublicPassengerForm) — no myairops pull needed. This demo
// stands in with simple generated placeholders per passenger instead of wiring the
// older, disconnected passenger-intake module.

import type { MyAirOpsTripSheet, PassengerTravelDocument } from './types';

function itineraryHtml(sheet: MyAirOpsTripSheet): string {
  const rows = sheet.legs
    .map((l, i) => `<li>Leg ${i + 1}: ${l.departure.icao} &rarr; ${l.arrival.icao} &mdash; ${l.etdLocal} local departure</li>`)
    .join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body style="font-family:Arial,sans-serif;margin:24px;">
    <h2>Passenger Itinerary &mdash; Trip ${sheet.tripNumber}</h2>
    <ul>${rows}</ul>
    <p style="color:#999;font-size:11px;">Generated by myGFO · demo content</p>
  </body></html>`;
}

function travelDocPlaceholderHtml(passengerName: string, docType: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body style="font-family:Arial,sans-serif;margin:24px;">
    <h2>${docType} &mdash; ${passengerName}</h2>
    <p style="color:#888;">Demo placeholder &mdash; in production this is the passenger's document already
    uploaded through myGFO's passenger intake form.</p>
  </body></html>`;
}

export function getPassengerTravelDocuments(sheet: MyAirOpsTripSheet): PassengerTravelDocument[] {
  const docs: PassengerTravelDocument[] = [];
  const allLegIds = sheet.legs.map((l) => l.legId);

  docs.push({
    id: `itinerary-${sheet.tripNumber}`,
    passengerName: 'All Passengers',
    docType: 'itinerary',
    displayName: `Passenger Itinerary — Trip ${sheet.tripNumber}`,
    legIds: allLegIds,
    htmlContent: itineraryHtml(sheet),
  });

  for (const pax of sheet.passengers) {
    docs.push({
      id: `passport-${sheet.tripNumber}-${pax.employeeNumber}`,
      passengerName: pax.name,
      docType: 'passport',
      displayName: `Travel Document — Passport — ${pax.name}`,
      legIds: pax.legIds,
      htmlContent: travelDocPlaceholderHtml(pax.name, 'Passport'),
    });
  }

  return docs;
}
