// Renders myairops trip-sheet data into a printable HTML document.
//
// Matches the existing demo convention (see tech-log/util/printRecord.ts): production
// would generate a real PDF server-side; for the demo a styled HTML document stands in
// and travels to ForeFlight's Files tab as "the file."

import type { MyAirOpsTripSheet, MyAirOpsLegSheet } from './types';

function legIndexLabel(sheet: MyAirOpsTripSheet, legId: string): number {
  return sheet.legs.findIndex((l) => l.legId === legId) + 1;
}

function renderLeg(leg: MyAirOpsLegSheet, index: number): string {
  const offset = (h: number) => `UTC${h >= 0 ? '+' : ''}${h}`;
  return `
    <div class="leg">
      <h3>Leg ${index + 1} &mdash; ${leg.departure.icao} &rarr; ${leg.arrival.icao}</h3>
      <div class="leg-grid">
        <div><span class="label">Day</span>${leg.dayOfWeek}</div>
        <div><span class="label">Passengers</span>${leg.paxCount}</div>
        <div><span class="label">Departure</span>${leg.departure.icao} &mdash; ${leg.departure.city}, ${leg.departure.country}</div>
        <div><span class="label">Arrival</span>${leg.arrival.icao} &mdash; ${leg.arrival.city}, ${leg.arrival.country}</div>
        <div><span class="label">ETD (Local / Zulu)</span>${leg.etdLocal} / ${leg.etdUtc.slice(11, 16)}Z (${offset(leg.etdUtcOffsetHours)})</div>
        <div><span class="label">ETA (Local / Zulu)</span>${leg.etaLocal} / ${leg.etaUtc.slice(11, 16)}Z (${offset(leg.etaUtcOffsetHours)})</div>
        <div><span class="label">Departure FBO</span>${leg.departureFbo.name} &mdash; ${leg.departureFbo.phone}</div>
        <div><span class="label">Arrival FBO</span>${leg.arrivalFbo.name} &mdash; ${leg.arrivalFbo.phone}</div>
        <div><span class="label">EFT / ETE</span>${leg.eft} / ${leg.ete}</div>
      </div>
      <div class="leg-notes">
        <div><span class="label">Leg Comments</span>${leg.legComments ?? '&mdash;'}</div>
        <div><span class="label">Pax Catering Requests</span>${leg.paxCateringRequests ?? '&mdash;'}</div>
        <div><span class="label">Scheduling Notes</span>${leg.schedulingNotes ?? '&mdash;'}</div>
      </div>
    </div>`;
}

export function renderTripSheetHtml(sheet: MyAirOpsTripSheet): string {
  const legsHtml = sheet.legs.map(renderLeg).join('\n');
  const crewHtml = sheet.crew
    .map((c) => `<tr><td>${c.role}</td><td>${c.name}</td><td>${c.phone}</td></tr>`)
    .join('');
  const paxHtml = sheet.passengers
    .map((p) => `
      <tr>
        <td>${p.name}</td><td>${p.employeeNumber}</td><td>${p.phone}</td><td>${p.nationality}</td>
        <td>${p.legIds.map((id) => legIndexLabel(sheet, id)).join(', ')}</td>
      </tr>`)
    .join('');
  const opsHtml = sheet.operationalMessages
    .map((m) => `<li><strong>${m.icao}</strong> &mdash; ${m.message}</li>`)
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Trip Sheet — ${sheet.tripNumber}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 24px; color: #1a1a1a; }
  h1 { margin-bottom: 4px; }
  .subhead { color: #555; margin-bottom: 20px; }
  h2 { border-bottom: 2px solid #030213; padding-bottom: 4px; margin-top: 28px; }
  .leg { border: 1px solid #ddd; border-radius: 8px; padding: 14px 16px; margin-bottom: 14px; }
  .leg h3 { margin-top: 0; }
  .leg-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 6px 24px; margin-bottom: 10px; }
  .leg-notes > div { margin-bottom: 4px; }
  .label { display: block; font-size: 11px; text-transform: uppercase; color: #888; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 13px; }
  th { background: #f5f5f7; }
  ul { padding-left: 18px; }
</style>
</head>
<body>
  <h1>Trip Sheet — ${sheet.tripNumber}</h1>
  <div class="subhead">${sheet.tail} &middot; ${sheet.aircraftType} &middot; ${sheet.tripDates.startDate.slice(0, 10)} to ${sheet.tripDates.endDate.slice(0, 10)}</div>

  <h2>Crew</h2>
  <table><thead><tr><th>Role</th><th>Name</th><th>Phone</th></tr></thead><tbody>${crewHtml}</tbody></table>

  <h2>Legs</h2>
  ${legsHtml}

  <h2>Passengers</h2>
  <table>
    <thead><tr><th>Name</th><th>Employee #</th><th>Phone</th><th>Nationality</th><th>Leg(s)</th></tr></thead>
    <tbody>${paxHtml}</tbody>
  </table>

  <h2>Operational Messages</h2>
  <ul>${opsHtml}</ul>

  <p style="margin-top:28px; color:#999; font-size:11px;">Generated by myGFO from myairops trip data · demo content</p>
</body>
</html>`;
}
